version: '3.12'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nicomatic-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aspirine13z
      POSTGRES_DB: alexis
      POSTGRES_STATEMENT_TIMEOUT: 600000    
      POSTGRES_LOCK_TIMEOUT: 300000        
      POSTGRES_IDLE_IN_TRANSACTION_SESSION_TIMEOUT: 600000 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 4G
        limits:
          cpus: '4'
          memory: 8G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s        
      timeout: 120s         
      retries: 5
      start_period: 30s    
    command: >
      postgres 
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c statement_timeout=600000
      -c lock_timeout=300000
      -c idle_in_transaction_session_timeout=600000
    stop_grace_period: 30s

  ollama:
    image: ollama/ollama:latest
    container_name: nicomatic-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_NUM_PARALLEL=1        
      - OLLAMA_MAX_LOADED_MODELS=1    
      - OLLAMA_FLASH_ATTENTION=1       
      - OLLAMA_GPU_LAYERS=999          
      - OLLAMA_KEEP_ALIVE=30m         
      - OLLAMA_MAX_VRAM=0            
      - OLLAMA_REQUEST_TIMEOUT=600
      - OLLAMA_LOAD_TIMEOUT=300
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --max-time 30 http://localhost:11434/api/tags || exit 1"]
      interval: 120s          
      timeout: 120s          
      retries: 3
      start_period: 240s     
    privileged: true
    shm_size: 2gb
    stop_grace_period: 120s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nicomatic-app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/extracted_best:/app/extracted_best
      - ${PWD}/extracted_best/lab:/app/extracted_best/lab
      - /tmp:/tmp
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 2G
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aspirine13z
      - POSTGRES_DB=alexis
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - DATA_DIR=/app/extracted_best
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - OMP_NUM_THREADS=8             
      - MKL_NUM_THREADS=8             
      - TORCH_NUM_THREADS=8            
      - AGENT_TIMEOUT=900              
      - LLM_TIMEOUT=600               
      - SYNTHESIS_TIMEOUT=600        
      - MAX_AGENTS=4 
      - OLLAMA_NUM_PARALLEL=1     
      - OLLAMA_MAX_LOADED_MODELS=1
      - DATABASE_TIMEOUT=600      
      - STREAMING_TIMEOUT=900        
      - UVICORN_TIMEOUT_KEEP_ALIVE=900 
      - UVICORN_TIMEOUT_GRACEFUL_SHUTDOWN=60 
      - FASTAPI_TIMEOUT=900           
      - HTTP_TIMEOUT=900               
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --max-time 30 http://localhost:8000/health || exit 1"]
      interval: 60s          
      timeout: 600s           
      retries: 3
      start_period: 180s     
    shm_size: 1gb
    security_opt:
      - seccomp:unconfined
    stop_grace_period: 120s
    stop_signal: SIGTERM

  model-init:
    image: curlimages/curl:latest
    container_name: model-initializer
    depends_on:
      ollama:
        condition: service_started 
    restart: "no"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Waiting for Ollama to be fully ready..."
        sleep 30
        
        # Function to check if model exists
        check_model() {
          curl -s --max-time 60 http://ollama:11434/api/tags | grep -q "$1"
        }
        
        # Check GPU availability
        echo "Checking GPU availability..."
        curl -s --max-time 30 http://ollama:11434/api/ps || echo "Could not check GPU status"
        
        echo "Pulling qwen3:4b model (this may take 30+ minutes on first run)..."
        if check_model "qwen3:4b"; then
          echo "qwen3:4b model already exists, skipping download"
        else
          timeout 3600 curl -X POST --max-time 3600 http://ollama:11434/api/pull -d '{"name":"qwen3:4b"}' || echo "qwen3:4b pull failed or timed out"
        fi
        
        echo "Pulling nomic-embed-text model..."
        if check_model "nomic-embed-text"; then
          echo "nomic-embed-text model already exists, skipping download"
        else
          timeout 1800 curl -X POST --max-time 1800 http://ollama:11434/api/pull -d '{"name":"nomic-embed-text"}' || echo "nomic-embed-text pull failed or timed out"
        fi
        
        # Verify GPU usage
        echo "Verifying GPU usage..."
        curl -s --max-time 30 http://ollama:11434/api/ps | grep -i gpu || echo "GPU verification completed"
        
        echo "Model initialization complete!"

volumes:
  postgres_data:
  ollama_data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: nicomatic-bridge
      com.docker.network.driver.mtu: 9000
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
